name: Remote Execution Tests

on:
  workflow_dispatch:
    inputs:
      fork:
        description: 'Fork name (e.g. Prague)'
        required: true
        default: 'Prague'
      rpc_endpoint:
        description: 'RPC endpoint URL'
        required: true
      rpc_chain_id:
        description: 'RPC chain ID'
        required: true
      rpc_seed_key:
        description: 'RPC seed key'
        required: true
      test_path:
        description: 'Path to tests to run (e.g. ./tests/prague/eip7251_consolidations)'
        required: true
        default: './tests/prague/eip7251_consolidations'

jobs:
  remote-execution:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          uv --version
          uv sync --all-extras
      
      - name: Setup solc 0.8.24
        run: uv run solc-select use 0.8.24 --always-install
      
      - name: Run remote execution tests
        run: |
          uv run execute remote \
            --fork=${{ inputs.fork }} \
            --rpc-endpoint=${{ inputs.rpc_endpoint }} \
            --rpc-chain-id=${{ inputs.rpc_chain_id }} \
            --rpc-seed-key=${{ inputs.rpc_seed_key }} \
            ${{ inputs.test_path }} 